-- Clears all player ratings, match history, and session history.
-- Does NOT drop tables, columns, constraints, or RLS policies -- run
-- supabase/schema.sql again if you need the schema itself recreated.
--
-- WARNING: irreversible. This permanently deletes every row in all three
-- tables. Run in the Supabase SQL editor only when you actually mean to
-- wipe the data (e.g. clearing out test rows before going live).
--
-- matches.session_id references game_sessions.id, so both must be
-- truncated together in one statement (or with `cascade`) -- truncating
-- game_sessions alone would fail with a foreign key violation.
truncate table public.matches, public.players, public.game_sessions;
